

// sample for ck

ktypo = [
    "1| 만 이년 후에 바로가 꿈을 꾼즉 자기가 하숫가에 섰는데",
    "2| 보니 아름답고 살진 일곱 암소가 하수에서 올라와 갈밭에서 뜯어벅고",
    "3| 그 뒤에 또 흉악하고 파리한 다른 일곱 암소가 하수에서 올라와 그 소와 함께 하숫가에 섰더니",
    "4| 그 흉악하고 파리한 소가 그 아름답고 살진 일곱 소를 먹은지라 바로가 곧 깨었다가",
    "5| 다시 잠이 들어 꿈을 꾸니 ㅎ ㅏㄴ 줄기에 무성하고 충실한 일곱 이삭이 나오고",
    "6| 그 후에 또 세약하고 동풍에 마른 일곱 이삭이 나오더니",
    "7| 그 세약한 일곱 이삭이 무성하고 충실한 일곱 이삭을 삼킨지라 바로가 깬즉 꿈이라",
    "8| 아침에 그 마음이 번민하여 보내어 애굽의 술객과 박사를 모두불러 그들에게 그 꿈을 고하였으나 그것을 바로에게 해석하는 자가 없었더라",
    "9| 술 맡은 관원장이 바로에게 고하여 가로되 내가 오늘날 나의 허물을 추억하나이다",
    "10| 바로께서 종들에게 노하사 나와 떡 굽는 관원장을 시위대장의 집에 가두셨을 때에",
    "11| 나와 그가 하룻밤에 꿈을 꾼즉 각기 징조가 있는 꿈이라",
    "12| 그곳에 시위대장의 종된 히브리 소년이 우리와 함께 있기로 우리가 그에게 고하매 그가 우리의 꿈을 풀되 그 꿈대로 각인에게 해석하더니",
    "13| 그 해석한대로 되어 나는 복직하고 그는 매여 달렸나이다",
    "14| 이에 바로가 보내어 요셉을 부르매 그들이 급히 그를 옥에서 낸지라 요셉이 곧 수염을 갂고 그 옷을 갈아 입고 바로에게 들어오니",
    "15| 바로가 요셉에게 이르되 내가 한 꿈을 꾸었으나 그것을 해석하는 자가 없더니 들은즉 너는 꿈을 들으면 능히 푼다더라",
    "16| 요셉이 바로에게 대답하여 가로되 이는 내게 있는 것이 아니라 하나님이 바로에게 평안한 대답을 하시리이다",
    "17| 바로가 요셉에게 이르되 내가 꿈에 하숫가에 서서",
    "18| 보니 살지고 아름다운 일곱 암소가 하숫가에 올라와 갈밭에서 뜯어 먹고",
    "19| 그 뒤에 또 약하고 심히 흉악하고 파리한 일곱 암소가 올라오니 그 같이 흉악한 것들은 애굽 땅에서 내가 아직 보지 못한 것이라",
    "20| 그 파리하고 흉악한 소가 처음의 일곱 살진 소를 먹었으며",
    "21| 먹었으나 먹은듯하지 아니하여 여전히 흉악하더라 내가 곧 깨었다가",
    "22| 다시 꿈에 보니 한 줄기에 무성하고 충실한 일곱 이삭이 나오고",
    "23| 그 후에 또 세약하고 동풍에 마른 일곱 이삭이 나더니",
    "24| 그 세약한 이ㅅㄱ이 좋은 일곱 이삭을 삼키더라 내가 그 꿈을 술객에게 말하였으나 그것을 내게 보이는 자가 없느니라",
    "25| 요셉이 바로에게 고하되 바로의 꿈은 하나이라 하나님이 그 하실 일을 바로에게 보이심이니이다",
    "26| 일곱 좋은 암소는 일곱해요 일곱 좋은 이삭도 일곱해니 그 꿈은 하나이라",
    "27| 그 후에 올라온 파리하고 흉악한 일곱 소는 칠년이요 동풍에 말라속이 빈 일곱 이삭도 이곱해 흉년이니",
    "28| 내가 바로에게 고하기를 하나님이 그 하실 일로 바로에게 보이신다 함이 이것이라",
    "29| 온 애굽 땅에 일곱해 큰풍년이 있겠고",
    "30| 후에 일곱해 흉년이 들므로 애굽 땅에 있던 풍년을 다 잊어버리게 되고 이 땅이 기근으로 멸망되리니",
    "31| 후에 든 그 흉년이 너무 심하므로 이전 풍년을 이 땅에서 기억하지 못하게 되리이다",
    "32| 바로께서 꿈을 두번 겹쳐 꾸신 것은 하나님이 이 일을 정하셨음이라 속히 행하시리니",
    "33| 이제 바로께서는 명철하고 지혜 있는 사람을 택하여 애굽 땅을 치리하게 하시고",
    "34| 바로께서는 또 이같이 행하사 국중에 여러 관리를 두어 그 일곱해 풍년에 애굽 땅의 오분의 일을 거두되",
    "35| 그 관리로 장차 올 풍년의 모든 곡물을 거두고 그 곡물을 바로의 손에 돌려 양식을 위하여 각 석ㅇ에 적치하게 하소서",
    "36| 이와 같이 그 곡물을 이 땅에 저장하여 애굽 땅에 임할 일곱해 흉년을 예비하시면 땅이 이 흉년을 인하여 멸망치 아니하리이다",
    "37| 바로와 그 모든 신하가 이 일을 좋게 여긴지라",
    "38| 바로가 그 신하들에게 이르되 이와 같이 하나님의 신이 감동한 사람을 우리가 어찌 얻을 수 있으리요 하고",
    "39| 요셉에게 이르되 하나님이 이 모든 것을 네게 보이셨으니 너와 같이 명철하고 지혜 있는 자가 없도다",
    "40| 너는 내 집을 치리하라 내 백성이 다 네 명을 복종하리니 나는 너보다 높음이 보좌 뿐이니라",
    "41| 바로가 또 요셉에게 이르되 내가 너로 애굽 온 땅을 총리하게 하노라 하고",
    "42| 자기의 인장 반지를 빼어 요셉의 손에 끼우고 그에게 세마포 옷을 입히고 금사슬을 목에 걸고",
    "43| 자기에게 있는 버금 수레에 그를 태우매 무리가 그 앞에서 소리 지르기를 엎드리라 하더라 바로가 그로 애굽 전국을 총리하게 하였더라",
    "44| 바로가 요셉에게 이르되 나는 바로라 애굽 온 땅에서 네 허락 없이는 수족을 놀릴 자가 없으리라 하고",
    "45| 그가 요셉의 이름을 사브낫바네아라 하고 또 온 제사장 보디베라의 딸 아스낫을 그에게 주어 아내를 삼게 하니라 요셉이 나가 애굽 온 땅을 순찰하니라",
    "46| 요셉이 애굽왕 바로 앞에 설 때에 삼십세라 그가 바로 앞을 떠나 애굽 온 땅을 순찰하니",
    "47| 일곱해 풍년에 토지 소출이 심히 많은지라",
    "48| 요셉이 애굽 땅에 있는 그 칠년 곡물을 거두어 각성에 저축하되 각성 주위의 밭의 곡물을 그 성중에 저장하매",
    "49| 저장한 곡식이 바다 모래 같이 심히 많아 세기를 그쳤으니 그 수가 한이 없음이었더라",
    "50| 흉년이 들기 전에 요셉에게 두 아들을 낳되 곧 온 제사장 보디베라의 딸 아스낫이 그에게 낳은지라",
    "51| 요셉이 그 장자의 이름을 므낫세라 하였으니 하나님이 나로 나의 모든 고난과 나의 아비의 온 집 일을 잊어버리게 하셨다 함이요",
    "52| 차자의 이름을 에브라임이라 하였으니 하나님이 나로 나의 수고한 땅에서 창성하게 하셨다 함이었더라",
    "53| 애굽 땅에 일곱해 풍년이 그치고",
    "54| 요셉의 말과 같이 일곱해 흉년이 들기 시작하매 각국에는 기근이 있으나 애굽 온 땅에는 식물이 있더니",
    "55| 애굽 온 땅이 주리매 백성이 바로에게 부르짖어 양식을 구하는지라 바로가 애굽 모든 백성에게 이르되 요셉에게 가서 그가 너희에게 이르는대로 하라 하니라",
    "56| 온 지면에 기근이 있으매 요셉이 모든 창고를 열고 애굽 백성에게 팔쌔 애굽 땅에 기근이 심하며",
    "57| 각국 백성도 양식을 사려고 애굽으로 들어와 요셉에게 이르렀으니 기근이 온 세상에 심함이었더라",
]

etypo = [
    "1| After two whole years, Pharaoh dreamed that he was standing by the Nile,",
    "2| and behold, there came up out of the Nile seven cows, attractive and plump, and they fed in the reed grass.",
    "3| And behold, seven other cows, ugly and thin, came up out of the Nile after them, and stood by the other cows on the bank of the Nile.",
    "4| And the ugly, thin cows ate up the seven attractive, plump cows. And Pharaoh awoke.",
    "5| And he fell asleep and dreamed a second time. And behold, seven ears of grain, plump and good, were growing on one stalk.",
    "6| And behold, after them sprouted seven ears, thin and blighted by the east wind.",
    "7| And the thin ears swallowed up the seven plump, full ears. And Pharaoh awoke, and behold, it was a dream.",
    "8| So in the morning his spirit was troubled, and he sent and called for all the magicians of Egypt and all its wise men. Pharaoh told them his dreams, but there was none who could interpret them to Pharaoh.",
    "9| Then the chief cupbearer said to Pharaoh, \"I remember my offenses today.",
    "10| When Pharaoh was angry with his servants and put me and the chief baker in custody in the house of the captain of the guard,",
    "11| we dreamed on the same night, he and I, each having a dream with its own interpretation.",
    "12| A young Hebrew was there with us, a servant of the captain of the guard. When we told him, he interpreted our dreams to us, giving an interpretation to each man according to his dream.",
    "13| And as he interpreted to us, so it came about. I was restored to my office, and the baker was hanged.\"",
    "14| Then Pharaoh sent and called Joseph, and they quickly brought him out of the pit. And when he had shaved himself and changed his clothes, he came in before Pharaoh.",
    "15| And Pharaoh said to Joseph, \"I have had a dream, and there is no one who can interpret it. I have heard it said of you that when you hear a dream you can interpret it.\"",
    "16| Joseph answered Pharaoh, \"It is not in me; God will give Pharaoh a favorable answer.\"",
    "17| Then Pharaoh said to Joseph, \"Behold, in my dream I was standing on the banks of the Nile.",
    "18| Seven cows, plump and attractive, came up out of the Nile and fed in the reed grass.",
    "19| Seven other cows came up after them, poor and very ugly and thin, such as I had never seen in all the land of Egypt.",
    "20| And the thin, ugly cows ate up the first seven plump cows,",
    "21| but when they had eaten them no one would have known that they had eaten them, for they were still as ugly as at the beginning. Then I awoke.",
    "22| I also saw in my dream seven ears growing on one stalk, full and good.",
    "23| Seven ears, withered, thin, and blighted by the east wind, sprouted after them,",
    "24| and the thin ears swallowed up the seven good ears. And I told it to the magicians, but there was no one who could explain it to me.\"",
    "25| Then Joseph said to Pharaoh, \"The dreams of Pharaoh are one; God has revealed to Pharaoh what he is about to do.",
    "26| The seven good cows are seven years, and the seven good ears are seven years; the dreams are one.",
    "27| The seven lean and ugly cows that came up after them are seven years, and the seven emptry ears blighted by hte east wind are also seven years of famine.",
    "28| It is as I told Pharaoh; God has shown to Pharaoh what he is about to do.",
    "29| There will come seven years of great plenty throughout all the land of Egypt,",
    "30| but after them there will arise seven years of famine, and all the plenty will be forgotten in the land of Egypt. The famine will consume the land,",
    "31| and the plenty will be unknown in the land by reason of the famine that will follow, for it will be very severe.",
    "32| And the doubling of Pharaoh's dream means that the thing is fixed by God, and God will shortly bring it about.",
    "33| Now therefore let Pharaoh select a discerning and wise man, and set him over the land of Egypt.",
    "34| Let Pharaoh proceed to appoint overseers over the land and take one-fifth of the produce of the land of Egypt during the seven plentiful years.",
    "35| And let them gather all the food of these good years that are coming and store up grain under the authority of Pharaoh for food in the cities, and let them keep it.",
    "36| That food shall be a reserve for the land against the seven years of famine that are to occur in the land of Egypt, so that the land may not perish through the famine.\"",
    "37| This proposal pleased Pharaoh and all his servants.",
    "38| And Pharaoh said to his servants, \"Can we find a man like this, in whom is the Spirit of God?\"",
    "39| Then Pharaoh said to Joseph, \"Since God has shown you all this, there is none so discerning and wise as you are.",
    "40| You shall be over my house, and all my people shall order themselves as you command. Only as regards the throne will I be greater than you.\"",
    "41| And Pharaoh said to Joseph, \"See, I have set you over all the land of Egypt.\"",
    "42| Then Pharaoh took his signet ring from his hand and put it on Joseph's hand, and clothed him in garments of fine linen and put a gold chain about his neck.",
    "43| And he made him ride in his second chariot. And they called out before him, \"Bow the knee!\" Thus he set him over all the land of Egypt.",
    "44| Moreover, Pharaoh said to Joseph, \"I am Pharaoh, and without your concent no one shall lift up hand or foot in all the land of Egypt.\"",
    "45| And Pharaoh called Joseph's name Zaphenath-paneah. And he gave him in marriage Asenath, the daughter of Potiphera priest of On. So Joseph went out over the land of Egypt.",
    "46| Joseph was thirty years old when he entered the service of Pharaoh king of Egypt. And Joseph went out from the presence of Pharaoh and went through all the land of Egypt.",
    "47| During the seven plentiful years the earth produced abundantly,",
    "48| and he gathered up all the food of these seven years, which occurred in the land of Egypt, and put the food in the cities. He put in every city the food from the fields around it.",
    "49| And Joseph stored up grain in great abundance, like the sand of the sea, until he ceased to measure it, for it could not be measured.",
    "50| Before the year of famine came, two sons were born to Joseph. Asenath, the daughter of Potiphera priest of On, bore them to him.",
    "51| Joseph called the name of the firstborn Manasseh. \"For,\" he said, \"God has made me forget all my hardship and all my father's house.\"",
    "52| The name of the second he called Ephraim, \"For God has made me fruitful in the land of my affliction.\"",
    "53| The seven years of plenty that occurred in the land of Egypt came to an end,",
    "54| and the seven years of famine began to come, as Joseph had said. There was famine in all lands, but in all the land of Egypt there was bread. There was famine in all lands, but in all the land of Egypt there was bread.",
    "55| When all the land of Egypt was famished, the people cried to Pharaoh for bread. Pharaoh said to all the Egyptians, \"Go to Joseph. What he says to do, do.\"",
    "56| So when the famine had spread over all the land, Joseph opened all the storehouses and sold to the Egyptians, for the famine was severe in the land of Egypt.",
    "57| Moreover, all the earth came to Egypt to Joseph to buy grain, because the famine was severe over all the earth.",
]